export const JOKES: string[] = [
  "Why do programmers prefer dark mode? Because light attracts bugs.",
  "There are only 10 kinds of people: those who understand binary and those who don't.",
  "A SQL query walks into a bar, approaches two tables and asks: may I join you?",
  "Why did the developer go broke? Because he used up all his cache.",
  "I would tell you a UDP joke, but you might not get it.",
  "Why do Java developers wear glasses? Because they can't C#.",
  "How many programmers does it take to change a light bulb? None, it's a hardware problem.",
  "!false — it's funny because it's true.",
  "Why was the JavaScript developer sad? Because he didn't Node how to Express himself.",
  "There's no place like 127.0.0.1.",
  "I'd tell you a TCP joke, but I'd have to keep repeating it until you got it.",
  "Debugging: being the detective in a crime movie where you are also the murderer.",
  "Why did the computer show up late to work? It had a hard drive.",
  "To understand what recursion is, you must first understand what recursion is.",
  "A byte walked into a doctor's office. The doctor said: sorry, you're not feeling yourself today.",
  "Why do Python programmers wear glasses? Because they can't C.",
  "The best thing about a Boolean is that even if you are wrong, you are only off by a bit.",
  "What is a programmer's favourite hangout place? Foo Bar.",
  "Why did the smartphone go to therapy? It lost its contacts.",
  "I changed my password to 'incorrect'. Now my computer reminds me every time I forget it.",
  "Why was the math book sad? It had too many problems.",
  "What do you call a fish without eyes? A fsh.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
];

export const FACTS: string[] = [
  "Honey never spoils — archaeologists have eaten 3,000-year-old honey found in Egyptian tombs.",
  "Octopuses have three hearts and blue blood.",
  "Bananas are berries, but strawberries are not.",
  "A day on Venus is longer than its year.",
  "Wombats produce cube-shaped poop.",
  "The Eiffel Tower can grow more than 15 cm taller in summer due to thermal expansion.",
  "Sharks existed before trees — by about 50 million years.",
  "There are more possible chess games than atoms in the observable universe.",
  "Scotland's national animal is the unicorn.",
  "Hot water can freeze faster than cold water — the Mpemba effect.",
  "Humans share about 60% of their DNA with bananas.",
  "Lightning strikes Earth roughly 8 million times per day.",
  "The Great Wall of China is not visible from the Moon with the naked eye.",
  "Antarctica is the largest desert on Earth.",
  "A group of flamingos is called a flamboyance.",
  "Sloths can hold their breath longer than dolphins — up to 40 minutes.",
  "The shortest war in history lasted between 38 and 45 minutes: Britain vs Zanzibar, 1896.",
  "Sea otters hold hands while sleeping so they don't drift apart.",
  "The first computer bug was an actual moth, logged by Grace Hopper's team in 1947.",
  "Neutron stars can spin up to 700 times per second.",
  "Your brain uses roughly 20% of your body's total energy.",
  "Butterflies taste with their feet.",
  "There are more trees on Earth than stars in the Milky Way — about 3 trillion vs 100 billion.",
  "Venus spins backwards compared to most other planets.",
  "Cows have best friends and get stressed when separated from them.",
  "The word 'robot' comes from the Czech word 'robota', meaning forced labour.",
  "Water can boil and freeze at the same time — the triple point.",
  "Some metals, like gallium, melt in your hand at body temperature.",
];

export const QUOTES: { text: string; author: string }[] = [
  { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "Talk is cheap. Show me the code.", author: "Linus Torvalds" },
  { text: "Programs must be written for people to read, and only incidentally for machines to execute.", author: "Harold Abelson" },
  { text: "Premature optimization is the root of all evil.", author: "Donald Knuth" },
  { text: "Any sufficiently advanced technology is indistinguishable from magic.", author: "Arthur C. Clarke" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Whether you think you can, or you think you can't — you're right.", author: "Henry Ford" },
  { text: "An Apple a day keeps you busy anyway.", author: "Sahil" },
  { text: "First, solve the problem. Then, write the code.", author: "John Johnson" },
  { text: "Experience is the name everyone gives to their mistakes.", author: "Oscar Wilde" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "What we know is a drop, what we don't know is an ocean.", author: "Isaac Newton" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "Make it work, make it right, make it fast.", author: "Kent Beck" },
  { text: "Perfection is achieved when there is nothing left to take away.", author: "Antoine de Saint-Exupery" },
  { text: "The best error message is the one that never shows up.", author: "Thomas Fuchs" },
  { text: "Weeks of coding can save you hours of planning.", author: "Unknown" },
  { text: "Simplicity is prerequisite for reliability.", author: "Edsger W. Dijkstra" },
  { text: "Do not go where the path may lead; go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
];

export const EMOJI: { char: string; name: string }[] = [
  { char: "😀", name: "grinning face" }, { char: "😂", name: "face with tears of joy" },
  { char: "🥲", name: "smiling face with tear" }, { char: "😎", name: "smiling face with sunglasses" },
  { char: "🤖", name: "robot" }, { char: "👻", name: "ghost" }, { char: "👽", name: "alien" },
  { char: "🎃", name: "jack-o-lantern" }, { char: "🐱", name: "cat face" }, { char: "🐶", name: "dog face" },
  { char: "🦊", name: "fox" }, { char: "🐻", name: "bear" }, { char: "🐼", name: "panda" },
  { char: "🐨", name: "koala" }, { char: "🦁", name: "lion" }, { char: "🐯", name: "tiger face" },
  { char: "🐮", name: "cow face" }, { char: "🐷", name: "pig face" }, { char: "🐸", name: "frog" },
  { char: "🐵", name: "monkey face" }, { char: "🦄", name: "unicorn" }, { char: "🐝", name: "honeybee" },
  { char: "🦋", name: "butterfly" }, { char: "🐙", name: "octopus" }, { char: "🦈", name: "shark" },
  { char: "🐬", name: "dolphin" }, { char: "🐳", name: "spouting whale" }, { char: "🐢", name: "turtle" },
  { char: "🦉", name: "owl" }, { char: "🦜", name: "parrot" }, { char: "🐧", name: "penguin" },
  { char: "🍕", name: "pizza" }, { char: "🍔", name: "hamburger" }, { char: "🍟", name: "french fries" },
  { char: "🌮", name: "taco" }, { char: "🍣", name: "sushi" }, { char: "🍜", name: "steaming bowl" },
  { char: "🍩", name: "doughnut" }, { char: "🍪", name: "cookie" }, { char: "🎂", name: "birthday cake" },
  { char: "☕", name: "hot beverage" }, { char: "🍵", name: "teacup without handle" }, { char: "🧋", name: "bubble tea" },
  { char: "🍺", name: "beer mug" }, { char: "🍷", name: "wine glass" }, { char: "🥑", name: "avocado" },
  { char: "🍉", name: "watermelon" }, { char: "🍓", name: "strawberry" }, { char: "🍍", name: "pineapple" },
  { char: "🌶️", name: "hot pepper" }, { char: "🌽", name: "ear of corn" }, { char: "🥕", name: "carrot" },
  { char: "🌍", name: "globe showing Europe-Africa" }, { char: "🌎", name: "globe showing Americas" },
  { char: "🌏", name: "globe showing Asia-Australia" }, { char: "🌙", name: "crescent moon" },
  { char: "⭐", name: "star" }, { char: "🌟", name: "glowing star" }, { char: "✨", name: "sparkles" },
  { char: "⚡", name: "high voltage" }, { char: "🔥", name: "fire" }, { char: "💧", name: "droplet" },
  { char: "🌈", name: "rainbow" }, { char: "☀️", name: "sun" }, { char: "⛅", name: "sun behind cloud" },
  { char: "🌧️", name: "cloud with rain" }, { char: "❄️", name: "snowflake" }, { char: "🌊", name: "water wave" },
  { char: "🚀", name: "rocket" }, { char: "🛸", name: "flying saucer" }, { char: "✈️", name: "airplane" },
  { char: "🚗", name: "automobile" }, { char: "🚲", name: "bicycle" }, { char: "⛵", name: "sailboat" },
  { char: "🏆", name: "trophy" }, { char: "🥇", name: "1st place medal" }, { char: "🎯", name: "bullseye" },
  { char: "🎮", name: "video game" }, { char: "🎲", name: "game die" }, { char: "🧩", name: "puzzle piece" },
  { char: "🎨", name: "artist palette" }, { char: "🎵", name: "musical note" }, { char: "🎸", name: "guitar" },
  { char: "📚", name: "books" }, { char: "✏️", name: "pencil" }, { char: "📝", name: "memo" },
  { char: "💡", name: "light bulb" }, { char: "🔍", name: "magnifying glass tilted left" },
  { char: "🔒", name: "locked" }, { char: "🔑", name: "key" }, { char: "🛠️", name: "hammer and wrench" },
  { char: "⚙️", name: "gear" }, { char: "🧠", name: "brain" }, { char: "👀", name: "eyes" },
  { char: "💪", name: "flexed biceps" }, { char: "🙏", name: "folded hands" }, { char: "👍", name: "thumbs up" },
  { char: "❤️", name: "red heart" }, { char: "💜", name: "purple heart" }, { char: "💚", name: "green heart" },
  { char: "💙", name: "blue heart" }, { char: "🖤", name: "black heart" }, { char: "🤍", name: "white heart" },
  { char: "💯", name: "hundred points" }, { char: "✅", name: "check mark button" }, { char: "❌", name: "cross mark" },
  { char: "⏰", name: "alarm clock" }, { char: "📅", name: "calendar" }, { char: "📍", name: "round pushpin" },
  { char: "💰", name: "money bag" }, { char: "🎁", name: "wrapped gift" }, { char: "🔔", name: "bell" },
  { char: "🌱", name: "seedling" }, { char: "🌸", name: "cherry blossom" }, { char: "🌵", name: "cactus" },
  { char: "🍄", name: "mushroom" }, { char: "🧀", name: "cheese wedge" }, { char: "🍞", name: "bread" },
];

export const LOREM_WORDS: string[] = [
  "lorem", "ipsum", "dolor", "sit", "amet", "consectetur", "adipiscing", "elit", "sed", "do",
  "eiusmod", "tempor", "incididunt", "ut", "labore", "et", "dolore", "magna", "aliqua", "enim",
  "ad", "minim", "veniam", "quis", "nostrud", "exercitation", "ullamco", "laboris", "nisi",
  "aliquip", "ex", "ea", "commodo", "consequat", "duis", "aute", "irure", "in", "reprehenderit",
  "voluptate", "velit", "esse", "cillum", "eu", "fugiat", "nulla", "pariatur", "excepteur",
  "sint", "occaecat", "cupidatat", "non", "proident", "sunt", "culpa", "qui", "officia",
  "deserunt", "mollit", "anim", "id", "est", "laborum",
];
